### ISSUE TITLE
failing on Roslyin with uncomprehensible errors

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#615] opened 2023-01-27 08:11 UTC
At the command line: 
```
$ git clone git@github.com:dotnet/roslyn.git
$ npx git-truck@latest 

Git Truck version 1.3.0 (latest)

✔ Git Truck started [249ms]
✔ Done checking for git repo [0ms]
✔ Succesfully opened Git Truck in your browser [10ms]

Application available at http://localhost:3000
✔ Done checking if path is a git repo [0ms]
✔ Done scanning for repositories [560ms]
GET / 200 - - 613.630 ms
✔ Found branch head [23ms]
✔ Commit tree analyzed [267ms]
✔ Commit tree hydrated [148.37s]
✔ Wrote data to /var/folders/n6/tryt30sd0n93yvv67t7yjc4h0000gn/T/git-truck/roslyn/main.json [532ms]
GET /roslyn/main?_data=routes%2F%24repo.%24 200 - - 151245.862 ms

```

In the browser: 

```
An error occured!

See console for more infomation.
bx@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:48406
Rd@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:48103
Id@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:50617
Ia/<@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:51404
yd@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:45701
i@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:117:50905
Dx@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:165:1432
Kd/p<@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:151:186
useMemo@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:6:25754
jt</S.useMemo@http://localhost:3000/build/_shared/chunk-2BPXJFRU.js:1:6766
Kd@http://localhost:3000/build/routes/$repo.$-7MSIYLH5.js:151:179
du@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:6:19484
Ba@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:44019
Ua@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:39726
Vf@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:39657
qr@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:39515
Qo@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:36662
pn@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:6:3250
Pe@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:8:33956
xf@http://localhost:3000/build/_shared/chunk-XMAWJ27N.js:6:24778
q@http://localhost:3000/build/_shared/chunk-2BPXJFRU.js:9:18357
h@http://localhost:3000/build/_shared/chunk-2BPXJFRU.js:9:5137
ie@http://localhost:3000/build/_shared/chunk-2BPXJFRU.js:9:12786
```

**Comment by joglr** [comment] 2023-01-29 11:27
We definitely need better error reporting, it's impossible to understand what goes wrong here. We have log levels that can be adjusted, but maybe we should write logs to the disk and ask to submit the error and it's logs in the UI?

**Comment by mircealungu** [comment] 2023-01-29 14:10
Figuring out a good error reporting approach would be nice.
Simplest might be using Sentry.io or similar?  
I'm using it for a backend but I'm sure they can also capture frontend errors.

**Comment by mircealungu** [comment] 2023-01-29 14:12
Although I wonder: if the code is minimized, then it won't help that it's centralized. 
I seem to vaguely remember a discussion we had in which somebody (you or @tjomson ) was suggesting to have a command-line argument that would run the non-minimized code?

**Comment by joglr** [comment] 2023-01-30 15:04
> Figuring out a good error reporting approach would be nice. Simplest might be using Sentry.io or similar? I'm using it for a backend but I'm sure they can also capture frontend errors.

Sentry works great for frontend, I created a project for git truck, but never set it up in the project. Source maps might help with the minification.

**Comment by mircealungu** [comment] 2023-01-30 17:04
Actually, the simplest thing would be to exclude our own code from the minification process. 
That way we have relevant info when there’s a crash and we still maintain the low footprint of the app for the libraries.

What say you?

**Comment by joglr** [comment] 2023-02-01 08:21
I cannot reproduce the error with roslyn
![image](https://user-images.githubusercontent.com/1959615/215988839-d330aa8d-7a36-4bc6-848d-9b714f7c3fb7.png)

**Comment by joglr** [comment] 2023-02-01 08:54
I just merged the PR that improves the application responsiveness and it is almost usable with the roslyn repo, compare to before 🥳

**Comment by mircealungu** [comment] 2023-02-01 09:48
Nice that it works for you!
I guess one more reason for trying to get the stack trace de-minimized!

**Closed** 2023-05-24 16:38 UTC
Labels: bug
