### ISSUE TITLE
riddle: can you spot the bug?

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#584] opened 2022-06-20 23:43 UTC
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/464519/174689543-4f0dcf1b-de8c-4fd2-950a-aa6d188871a8.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/464519/174689566-cd6a186f-feb1-41e3-bef0-ca1708dc3067.png">

**Comment by tjomson** [comment] 2022-06-22 08:01
Colors are not consistent when changing branch? #513

**Comment by mircealungu** [comment] 2022-06-22 09:06
you're both right. Unfortunately, circle positions are probably much harder to solve than colors

**Comment by joglr** [comment] 2022-06-22 09:23
> you're both right. Unfortunately, circle positions are probably much harder to solve than colors

Yes. Wattenberger solved it by using D3 Physics

**Comment by joglr** [comment] 2022-11-11 10:27
Duplicate of #547

**Closed by joglr** 2022-11-11 10:27 UTC
