### ISSUE TITLE
folder - click vs. doubleclick

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#396] opened 2022-03-23 13:57 UTC
- click could be select; and then we could filter also folders
- double-click could be zoom in

however, not sure that anybody could discover this on their own; so a little question mark icon with the most basic help popup page might be useful if we're to release it to the world

**Comment by tjomson** [comment] 2022-05-15 11:48
duplicate of #456

**Closed by tjomson** 2022-05-15 11:48 UTC
Labels: duplicate
