### ISSUE TITLE
Fix npx 404 for some systems (Thomas' funky problems)

### ISSUE THREAD

**Issue by hojelse** [git-truck/git-truck#368] opened 2022-03-18 13:50 UTC

**Comment by tjomson** [comment] 2022-03-21 08:12
![billede](https://user-images.githubusercontent.com/23435481/159224345-419120ed-52bc-4f10-b775-1726a306571f.png)

**Comment by joglr** [comment] 2022-04-15 21:52
Can you try reproduce with `npx git-truck@0.8.14-0` ? If you can't reproduce, then #506 might have fixed it.

**Comment by tjomson** [comment] 2022-04-16 08:28
It still says "express server listening", so it is just funky. Closing this issue, because most likely is caused by some old version i have locally

**Closed by tjomson** 2022-04-16 08:28 UTC
Labels: bug
